Hw14 calendar
RomanSarvarov/otus_go_home_work pull request #15
Opened 2022-10-06 19:26 UTC by RomanSarvarov

## Домашнее задание №14 «Кроликизация Календаря»

### Критерии оценки
- [ ] Makefile заполнен и пайплайн зеленый - 1 балл
- [ ] Работа с RMQ выделена в отдельный пакет, код не дублируется - 1 балл
- [ ] Реализован Рассыльщик - 2 балла
- [ ] Можно собрать сервисы одной командой (`make build`) - 1 балл
- [ ] Понятность и чистота кода - до 2 баллов

Реализован Планировщик:
- [ ] отсылает уведомления о выбранных событиях - 2 балла
- [ ] удаляет старые события - 1 балл

#### Зачёт от 7 баллов

2022-10-15 19:03 UTC, RomanSarvarov commented on hw12_13_14_15_calendar/Dockerfile
> +RUN echo
заметил что забрыл тут это убрать, убрал в следующем ДЗ

2022-10-30 14:45 UTC, romsar commented on hw12_13_14_15_calendar/docker-compose.yml
> +#  app:
мне удобнее разрабатывать без приложения Го в контейнере
в следующем ДЗ, где уже по ТЗ надо сделать контейнеризацию, вернул.

2022-10-31 17:41 UTC, dshemin requested changes

2022-10-31 17:41 UTC, dshemin commented on hw12_13_14_15_calendar/cmd/calendar_scheduler/main.go
> +			if err := repo.Close(); err != nil {
Если мы никак не обрабатываем ошибку, то можно её сразу вернуть без `if err != nil`. Вот так: `return repo.Close()`

2022-10-31 17:41 UTC, dshemin commented on hw12_13_14_15_calendar/scheduler/scheduler.go
> +type Model interface {
Смущает название интерфейса. Наверно будет более удачно назвать его `Repository`.

2022-10-31 17:41 UTC, dshemin commented on hw12_13_14_15_calendar/scheduler/scheduler.go
> +	WriteMessages(ctx context.Context, msgs ...kafka.Message) error
Тут у вас есть абстракция над брокером, но всё равно есть привязка к конкретной реализации - kafka. Следует тогда объявить свою структуру `Message`.

2022-10-31 17:41 UTC, dshemin commented on hw12_13_14_15_calendar/scheduler/scheduler.go
> +			select {
Как я описывал в другом ревью, стоит объединить эти два select'а в один

2022-10-31 17:41 UTC, dshemin commented on hw12_13_14_15_calendar/scheduler/scheduler.go
> +	ticker := time.NewTicker(s.cfg.Interval)
Как я понял, у вас один тикер на отправку и удаление старых. Тикер возвращает нам канал, давайте вспомним как работает конкурентное чтение из одного канала. Допустим наш пример, есть один канал и из него читает две горутины. Когда мы запишим что-то в канал, что произойдёт?

2022-10-31 17:41 UTC, dshemin commented on hw12_13_14_15_calendar/scheduler/scheduler.go
> +			for _, e := range events {
Если у нас будет N "протухщих" событий, то мы сделаем N запросов в БД. Это не самый хороший алгоритм. Мы можем удалить все просроченные события за один запрос. Более того, можем это сделать без выборки. Попробуйте составить такой SQL запрос.

2022-10-31 17:41 UTC, dshemin commented on hw12_13_14_15_calendar/scheduler/scheduler.go
> +	if err := errGrp.Wait(); err != nil {
Можно просто сделать `return errGrp.Wait()`

2022-10-31 17:41 UTC, dshemin commented on hw12_13_14_15_calendar/sender/sender.go
> +type Model interface {
Будет более правильно назвать это `Repository`

2022-10-31 17:41 UTC, dshemin commented on hw12_13_14_15_calendar/sender/sender.go
> +	if err := errGrp.Wait(); err != nil {
`return errGrp.Wait()`

2022-10-31 17:41 UTC, dshemin commented on hw12_13_14_15_calendar/postgres/event.go
> +		where, args = append(where, "is_notified = $"+strconv.Itoa(counter)), append(args, false)
Крайне неудобно читать такие конструкции. Лучше сделайте в две строки.

2022-10-31 17:41 UTC, dshemin commented on hw12_13_14_15_calendar/kafka/kafka.go
> +var TCP = kafka.TCP
Не совсем уловил суть. Для чего нам делать такие reimport'ы?

2022-10-31 17:41 UTC, dshemin commented on hw12_13_14_15_calendar/inmem/event.go
> +var TimeNowFunc func() time.Time
Можно сильно упростить, написав `var TimeNowFunc = time.Now`. Плюс у меня есть сомнение что это должна быть публичной переменной так, как из любого места проекта мы сможем её подменить.

Более удачным решением будет, добавить эту функцию как поле структуры Repository:

```
struct Repository {
    ...
    now func() time.Time
    ...
}

func NewRepository() *Repository {

     return &Repository {
         ...
         now: time.Now,
         ...
     }
}
```

2022-11-01 18:28 UTC, romsar commented on hw12_13_14_15_calendar/cmd/calendar_scheduler/main.go
> +			if err := repo.Close(); err != nil {
Ок

2022-11-01 18:29 UTC, romsar commented on hw12_13_14_15_calendar/scheduler/scheduler.go
> +type Model interface {
Ок

2022-11-01 18:41 UTC, romsar commented on hw12_13_14_15_calendar/scheduler/scheduler.go
> +	WriteMessages(ctx context.Context, msgs ...kafka.Message) error
Переделал, спасибо

2022-11-01 18:42 UTC, romsar commented on hw12_13_14_15_calendar/scheduler/scheduler.go
> +			select {
Объединил.

2022-11-01 18:42 UTC, romsar commented on hw12_13_14_15_calendar/scheduler/scheduler.go
> +	ticker := time.NewTicker(s.cfg.Interval)
Рандом произойдет, полагаю :(

2022-11-01 19:04 UTC, romsar commented on hw12_13_14_15_calendar/scheduler/scheduler.go
> +	ticker := time.NewTicker(s.cfg.Interval)
Переделал на 2 канала, спасибо!

2022-11-01 19:18 UTC, romsar commented on hw12_13_14_15_calendar/scheduler/scheduler.go
> +			for _, e := range events {
Исправил.

2022-11-01 19:19 UTC, romsar commented on hw12_13_14_15_calendar/scheduler/scheduler.go
> +	if err := errGrp.Wait(); err != nil {
Ок

2022-11-01 19:20 UTC, romsar commented on hw12_13_14_15_calendar/sender/sender.go
> +type Model interface {
Ок

2022-11-01 19:20 UTC, romsar commented on hw12_13_14_15_calendar/sender/sender.go
> +	if err := errGrp.Wait(); err != nil {
Ок

2022-11-01 19:22 UTC, romsar commented on hw12_13_14_15_calendar/postgres/event.go
> +		where, args = append(where, "is_notified = $"+strconv.Itoa(counter)), append(args, false)
Не соглашусь, удобно.
Я это подхватил от Бэна Джонсона https://github.com/benbjohnson/wtf/blob/main/sqlite/user.go#L143

2022-11-01 19:22 UTC, romsar commented on hw12_13_14_15_calendar/kafka/kafka.go
> +var TCP = kafka.TCP
Надо было чтобы в main когда конфиг задаешь не импортировать оригинальный пакет Кафка.
Щас я все этого абстрогировал.

2022-11-01 19:24 UTC, romsar commented on hw12_13_14_15_calendar/inmem/event.go
> +var TimeNowFunc func() time.Time
Это было больше месяца назад, сейчас я уже осознал что лучше так (глобально) не делать, потому что не получается делать параллельные тесты.
Но давайте я исправлю только импорт публичной переменной, чтобы не переделывать текущую реализацию.

2022-11-02 01:41 UTC, dshemin requested changes

2022-11-02 01:41 UTC, dshemin commented on hw12_13_14_15_calendar/inmem/event.go
> +func init() {
init уже не нужен, мы установили функцию так, как нам надо.

2022-11-02 07:27 UTC, romsar commented on hw12_13_14_15_calendar/inmem/event.go
> +func init() {
ага, не увидел

2022-11-02 09:08 UTC, merged