Hw15 calendar
RomanSarvarov/otus_go_home_work pull request #16
Opened 2022-10-17 18:56 UTC by RomanSarvarov

## Домашнее задание №15 «Докеризация и интеграционное тестирование Календаря»

### Критерии оценки
- [ ] Проект полностью запускается и останавливается с помощью `make up` / `make down` - 3 балла
- [ ] Интеграционные тесты запускаются с помощью `make integration-tests`. Команда возвращает верный код ответа - 1 балл

Интеграционные тесты покрывают бизнес сценарии:
- [ ] добавление события и обработка бизнес ошибок - 2 балла
- [ ] получение листинга событий на день/неделю/месяц - 2 балла
- [ ] отправка уведомлений - 2 балла

#### Зачёт от 7 баллов

2022-10-31 09:18 UTC, dshemin requested changes

2022-10-31 09:18 UTC, dshemin commented on hw12_13_14_15_calendar/Makefile
> +	chmod +x ./scripts/run-integration-test.sh && ./scripts/run-integration-test.sh
Можно сразу выставить флаг выполнения и закомитить. Или запускать через интерпретатор вот так: `sh ./scripts/run-integration-test.sh`.

2022-10-31 09:18 UTC, dshemin commented on hw12_13_14_15_calendar/sender/sender.go
> +	ReadMessage(ctx context.Context) (kafka.Message, error)
Вы сделали интерфейс для брокера, это хорошо. Вот только проблема в том, что возвращаемое значение -  kafka.Message - всё равно привязвает нас к  конкретной реализации. Нужно добавить абстракцию и тут, например в виде создания структуры данных EventMessage.

2022-10-31 09:18 UTC, dshemin commented on hw12_13_14_15_calendar/scheduler/scheduler.go
> +		for {
Тут вы можете обойтись только одним `select`:
```
for {
    select {
        case <-ctx.Done():
           ...
        case <-tiker.C:
           if err = fn(); err != nil {
               return err
           }
    }
}
```

2022-10-31 09:18 UTC, dshemin commented on hw12_13_14_15_calendar/scheduler/scheduler.go
> +				return nil
Желательно всё же вернуть тут ctx.Err()

2022-10-31 09:18 UTC, dshemin commented on hw12_13_14_15_calendar/build/sender.Dockerfile
> +FROM golang:1.16-alpine AS builder
Обратите внимание, у вас все три докерфайла крайне похожи. Тут можно попробовать применить https://docs.docker.com/engine/reference/builder/#arg

2022-10-31 09:25 UTC, romsar commented on hw12_13_14_15_calendar/Makefile
> +	chmod +x ./scripts/run-integration-test.sh && ./scripts/run-integration-test.sh
АААА
Дмитрий, вы проверяете сразу два МР.

2022-10-31 09:26 UTC, romsar commented on hw12_13_14_15_calendar/Makefile
> +	chmod +x ./scripts/run-integration-test.sh && ./scripts/run-integration-test.sh
Там же еще 14 висит (предыдущее ДЗ).
А эта ветка от ветки 14.
Вы щас за две ДЗ смотрите, 14 еще в проверку не бралась.

2022-10-31 09:26 UTC, romsar commented on hw12_13_14_15_calendar/sender/sender.go
> +	ReadMessage(ctx context.Context) (kafka.Message, error)
Опять таки, это относится к предыдущему ДЗ.
Или вы сразу 2 проверяете и мне решать в рамках этой таски?

2022-10-31 09:30 UTC, romsar commented on hw12_13_14_15_calendar/scheduler/scheduler.go
> +				return nil
Разве так не будет всегда ошибка ErrContextCancelled  (или как-то так) всегда? В чем смысл...
Ок, исправлю.

2022-10-31 09:57 UTC, dshemin commented on hw12_13_14_15_calendar/Makefile
> +	chmod +x ./scripts/run-integration-test.sh && ./scripts/run-integration-test.sh
Я прошёл по ссылке в сообщении, видимо где-то ошибка. Посмотрю позже предыдущий пулл.

2022-10-31 10:04 UTC, romsar commented on hw12_13_14_15_calendar/Makefile
> +	chmod +x ./scripts/run-integration-test.sh && ./scripts/run-integration-test.sh
<img width="383" alt="image" src="https://user-images.githubusercontent.com/27378369/198982998-ba354a1e-b2a7-4dff-81eb-e55f4e9d3109.png">
Все вы правильно перешли, но только надо проверять сначало 14.
Календарь - это 4 дз, которые надо проверять по порядку.

2022-11-01 19:49 UTC, romsar commented on hw12_13_14_15_calendar/Makefile
> +	chmod +x ./scripts/run-integration-test.sh && ./scripts/run-integration-test.sh
Исправил.

2022-11-01 19:50 UTC, romsar commented on hw12_13_14_15_calendar/scheduler/scheduler.go
> +		for {
Исправил в рамках предыдущего МР.

2022-11-01 19:51 UTC, romsar commented on hw12_13_14_15_calendar/scheduler/scheduler.go
> +				return nil
Исправил.

2022-11-01 23:01 UTC, romsar commented on hw12_13_14_15_calendar/build/sender.Dockerfile
> +FROM golang:1.16-alpine AS builder
Ок

2022-11-01 23:04 UTC, romsar commented on hw12_13_14_15_calendar/sender/sender.go
> +	ReadMessage(ctx context.Context) (kafka.Message, error)
Абстрагировал ReadMessage

2022-11-02 08:36 UTC, dshemin approved these changes

2022-11-02 08:37 UTC, dshemin approved these changes

2022-11-02 09:06 UTC, romsar commented
Дмитрий, вы заапрувили оба мр, но в Отусе в ЛК только 14 ДЗ поставили как зачтенное(

2022-11-02 09:08 UTC, merged